version: '3.7'
services:
  app:
    build:
      target: prod
    volumes:
      - type: bind
        source: ./public
        target: /usr/src/app/public
    restart: always
    ports:
      - 5041:4001
  nginx:
    restart: always
    volumes:
      - type: bind
        source: ./config/nginx/nginx.prod.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - 5001:80
  postgres:
    restart: always
  redis:
    restart: always
